# Generated by Django 4.2.1 on 2023-05-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_profile_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='static/img/icon.png', upload_to='media/%Y/%M/profile_img/'),
        ),
    ]
